#include <ansi.h>
inherit SKILL;
mapping *quest = ({
        ([      "quest":                "¹´»êÊ¹Õß",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "°×ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "ÎÚÄ¾ô¢",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "ëÙËÉ",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "·¨»ª¾­",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "½ð¹âÃ÷¾­",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "·¨¾ä",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "Äàºã",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "·¨º£²Ø",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "Äá°×ÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "³àËÉ",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "ÀÏÕÅ",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "µûÁµ»¨½£·¨ÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "Ò»¼ôÃ·»¨ÊÖÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "¶Ì¸èµ¶·¨ÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "ÄÚ¹¦ÐÄ·¨ÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "Çï·ç²½·¨ÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "ÆåµÀÃØóÅ",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "Ê¯Ñã",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "×Ï½ð¹Ú",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "°ËØÔµÀÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "ÆßÐÇ½£",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "µØÀûÀÏÈË",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "½ðÂÆÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "ÌìÊ±ÀÏÈË",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "ÈËºÍÀÏÈË",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "ÒøÂÆÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "ÌúÂÆÒÂ",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "Ñ¦ÍÓ×Ó",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "ÒÒ³ÉÏÉ",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "Ì«¼«°ËØÔµÀÅÛ",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "Ìú´«¼×",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "ÆÕÉú",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "»¨Âú³Ç",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "Á¦Ê¿",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "½ð¸ÕèÆ",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "±¦¹Ú",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "ÌÆ¿ÉÇä",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "Àäºì¶ù",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "ÀäÑª´Ì¿Í",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "»¨ÏÉ",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "Ã½ÆÅ",
                "quest_type":           "É±",
                "exp_bonus":            70,
        ]),
        ([      "quest":                "ÇàÒÂ·þ",
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),
        ([      "quest":              HIG "ÇàÒÂ´Ì" NOR,
                "quest_type":           "Ñ°",
                "exp_bonus":            70,
        ]),

});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

